services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  
  web:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/static
    ports:
      - "80:80"
    depends_on:
      - app